ALTER TABLE ITEM
    ALTER COLUMN NAME VARCHAR(50);

ALTER TABLE SALES_ORDER_LINE
    ADD COLUMN DELIVERY_ADDRESS INT4;

ALTER TABLE SALES_ORDER_LINE
    DROP COLUMN DELIVERY_ADDRESS;

ALTER TABLE SALES_ORDER
    ADD COLUMN DELIVERY_ADDRESS INT4;

UPDATE SALES_ORDER S
SET DELIVERY_ADDRESS = (SELECT A.ID FROM ADDRESS A WHERE A.CUSTOMER_ID = S.CUSTOMER_ID LIMIT 1);

ALTER TABLE SALES_ORDER
    ALTER COLUMN DELIVERY_ADDRESS SET NOT NULL;
