EXPLAIN
SELECT *
FROM CUSTOMER
WHERE NAME = 'CNH';

ALTER TABLE CUSTOMER
    ADD CONSTRAINT UK_NAME UNIQUE (NAME);

CREATE INDEX IDX_NAME ON CUSTOMER (NAME);

ALTER TABLE ADDRESS
    ALTER COLUMN CITY SET NOT NULL;

EXPLAIN
SELECT *
FROM ITEM
WHERE NAME LIKE '%Bearing%'
  AND PRICE > 1;

CREATE INDEX IDX_PRICE ON ITEM (PRICE);
CREATE INDEX IDX_NAME_PRICE ON ITEM (NAME, PRICE);
drop INDEX  IDX_NAME_PRICE;

EXPLAIN
SELECT *
FROM ITEM
WHERE NAME = 'Bearing'
  AND PRICE > 1;