SELECT *
FROM CUSTOMER
WHERE ID NOT IN (
    SELECT CUSTOMER_ID
    FROM ADDRESS
    WHERE COUNTRY <> 'Belgium');

SELECT *
FROM CUSTOMER C
WHERE NOT exists(
        SELECT A.CUSTOMER_ID
        FROM ADDRESS A
        WHERE C.ID = A.CUSTOMER_ID
          AND COUNTRY <> 'Belgium');

SELECT *
FROM CUSTOMER
WHERE ID IN (
    SELECT CUSTOMER_ID
    FROM ADDRESS
    WHERE COUNTRY = 'Belgium')
  AND ID IN (
    SELECT CUSTOMER_ID
    FROM ADDRESS
    WHERE COUNTRY <> 'Belgium');

SELECT *
FROM CUSTOMER
WHERE ID IN (SELECT CUSTOMER_ID
             FROM SALES_ORDER
             GROUP BY CUSTOMER_ID
             ORDER BY count(*) DESC
             LIMIT 1);

SELECT *
FROM CUSTOMER
WHERE ID = (
    SELECT CUSTOMER_ID
    FROM SALES_ORDER
    WHERE ORDER_ID =
          (SELECT ORDER_ID
           FROM SALES_ORDER_LINE
           GROUP BY ORDER_ID
           ORDER BY sum(PRICE) DESC
           LIMIT 1));