UPDATE CUSTOMER
SET GRADE      = 99,
    UPDATED_ON = NOW()
WHERE NAME = 'IKEA';

SELECT S.CUSTOMER_ID, C.NAME, S.ORDER_ID, S.STATUS
FROM CUSTOMER C
         JOIN SALES_ORDER S ON S.CUSTOMER_ID = C.ID;

SELECT * from SALES_ORDER_LINE WHERE ORDER_ID = '2';
