SELECT *
FROM CUSTOMER
         JOIN ADDRESS A ON CUSTOMER.ID = A.CUSTOMER_ID;

SELECT *
FROM CUSTOMER
         JOIN SALES_ORDER ON CUSTOMER.ID = SALES_ORDER.CUSTOMER_ID;


SELECT C.NAME, S.ORDER_ID, S.STATUS, S.CREATED_ON
FROM CUSTOMER C
         LEFT JOIN SALES_ORDER S ON C.ID = S.CUSTOMER_ID
WHERE C.GRADE <= 70;

SELECT C.NAME, S.ORDER_ID, S.STATUS, S.CREATED_ON
FROM CUSTOMER C
         JOIN SALES_ORDER S ON C.ID = S.CUSTOMER_ID
         JOIN ADDRESS A ON C.ID = A.CUSTOMER_ID
WHERE C.GRADE < 80
  AND C.NAME = 'IKEA'
  AND A.COUNTRY = 'Belgium';

SELECT A.CUSTOMER_ID, C.NAME, C.ISO_CODE
FROM ADDRESS A
         RIGHT JOIN COUNTRY C ON A.COUNTRY = C.NAME
WHERE A.COUNTRY IS NULL;

SELECT NAME
FROM CUSTOMER
WHERE GRADE > 70
UNION
SELECT NAME
FROM PERSON;

SELECT C.NAME, C.GRADE
FROM CUSTOMER C
         JOIN ADDRESS A ON C.ID = A.CUSTOMER_ID
WHERE A.COUNTRY = 'The Netherlands';

SELECT S.CUSTOMER_ID, C.NAME, S.ORDER_ID, S.STATUS
FROM CUSTOMER C
         JOIN ADDRESS A ON C.ID = A.CUSTOMER_ID AND A.COUNTRY = 'The Netherlands'
         JOIN SALES_ORDER S ON S.CUSTOMER_ID = C.ID;

SELECT S.CUSTOMER_ID, C.NAME, S.ORDER_ID, S.STATUS, sum(PRICE) AS TOTAL_PRICE
FROM CUSTOMER C
         JOIN ADDRESS A ON C.ID = A.CUSTOMER_ID AND A.COUNTRY = 'The Netherlands'
         JOIN SALES_ORDER S ON S.CUSTOMER_ID = C.ID
         JOIN SALES_ORDER_LINE L ON S.ORDER_ID = L.ORDER_ID
GROUP BY S.CUSTOMER_ID, C.NAME, S.ORDER_ID, S.STATUS;

SELECT C.*
FROM CUSTOMER C
         JOIN ADDRESS A1 ON C.ID = A1.CUSTOMER_ID
         JOIN ADDRESS A2 ON A1.CITY = A2.CITY AND A1.CUSTOMER_ID <> A2.CUSTOMER_ID;

SELECT C.NAME, S.ORDER_ID, S.STATUS, S.CREATED_ON
FROM CUSTOMER C
         LEFT JOIN SALES_ORDER S ON C.ID = S.CUSTOMER_ID
WHERE S.CUSTOMER_ID IS NULL;

SELECT *
FROM SALES_ORDER
         JOIN ADDRESS ON SALES_ORDER.DELIVERY_ADDRESS = ADDRESS.ID;
