SELECT *
FROM CUSTOMER
WHERE ID NOT IN (
    SELECT CUSTOMER_ID
    FROM ADDRESS
    WHERE COUNTRY <> 'Belgium');

SELECT *
FROM CUSTOMER
WHERE ID IN (
    SELECT CUSTOMER_ID
    FROM ADDRESS
    WHERE COUNTRY = 'Belgium')
  AND ID IN (
    SELECT CUSTOMER_ID
    FROM ADDRESS
    WHERE COUNTRY <> 'Belgium');