ALTER TABLE ITEM
    ALTER COLUMN NAME VARCHAR(50);

ALTER TABLE SALES_ORDER_LINE
    ADD COLUMN DELIVERY_ADDRESS INT4;

ALTER TABLE SALES_ORDER_LINE
    DROP COLUMN DELIVERY_ADDRESS;

ALTER TABLE SALES_ORDER
    ADD COLUMN DELIVERY_ADDRESS INT4;

UPDATE SALES_ORDER S
SET DELIVERY_ADDRESS = (SELECT A.ID FROM ADDRESS A WHERE A.CUSTOMER_ID = S.CUSTOMER_ID LIMIT 1);

ALTER TABLE SALES_ORDER
    ALTER COLUMN DELIVERY_ADDRESS SET NOT NULL;

SELECT *
FROM SALES_ORDER S
WHERE exists(SELECT * FROM CUSTOMER C WHERE C.ID = S.CUSTOMER_ID AND C.NAME = 'IKEA');

SELECT *
FROM ADDRESS A
WHERE A.COUNTRY = 'The Netherlands'
  AND exists(SELECT * FROM CUSTOMER C WHERE A.CUSTOMER_ID = C.ID AND C.NAME = 'IKEA');