UPDATE CUSTOMER
SET GRADE      = 99,
    UPDATED_ON = NOW()
WHERE NAME = 'IKEA';

UPDATE SALES_ORDER S
SET S.STATUS = 'IN_PROGRESS'
WHERE exists(SELECT * FROM CUSTOMER C WHERE S.CUSTOMER_ID = C.ID AND C.NAME = 'Firma Beel');

SELECT S.CUSTOMER_ID, C.NAME, S.ORDER_ID, S.STATUS
FROM CUSTOMER C
         JOIN SALES_ORDER S ON S.CUSTOMER_ID = C.ID;

SELECT *
FROM SALES_ORDER_LINE
WHERE ORDER_ID = '2';
