SELECT *
FROM ITEM
ORDER BY PRICE DESC
LIMIT 1;

SELECT *
FROM ITEM
ORDER BY PRICE
LIMIT 1;

SELECT ITEM_ID, SUM(QUANTITY) AS AMOUNT
FROM SALES_ORDER_LINE
GROUP BY ITEM_ID
ORDER BY AMOUNT ASC
LIMIT 1;

SELECT ITEM_ID, sum(QUANTITY) AS AMOUNT
FROM SALES_ORDER_LINE
GROUP BY ITEM_ID
//HAVING AMOUNT > 15;
ORDER BY AMOUNT DESC
LIMIT 1;

SELECT count(*) AS COUNT, ITEM_ID
FROM SALES_ORDER_LINE
GROUP BY ITEM_ID
ORDER BY COUNT DESC
LIMIT 1;

SELECT count(*) AS COUNT, ITEM_ID
FROM SALES_ORDER_LINE
GROUP BY ITEM_ID
ORDER BY COUNT
LIMIT 1;

SELECT count(*) AS COUNT, CUSTOMER_ID
FROM SALES_ORDER
GROUP BY CUSTOMER_ID
ORDER BY COUNT DESC
LIMIT 1;

SELECT count(DISTINCT (CUSTOMER_ID)) AS COUNT, COUNTRY
FROM ADDRESS
GROUP BY COUNTRY;

SELECT sum(PRICE) AS TOTAL_PRICE, ORDER_ID
FROM SALES_ORDER_LINE
GROUP BY ORDER_ID
ORDER BY TOTAL_PRICE DESC;

// orders larger then 300
SELECT sum(PRICE) AS TOTAL_PRICE, ORDER_ID
FROM SALES_ORDER_LINE
GROUP BY ORDER_ID
HAVING TOTAL_PRICE > 300
ORDER BY TOTAL_PRICE DESC;

SELECT count(*) AS NBR_OF_CUSTOMERS, GRADE
FROM CUSTOMER
GROUP BY GRADE
HAVING  NBR_OF_CUSTOMERS > 5;
