SELECT *
FROM ITEM
ORDER BY PRICE DESC
LIMIT 1;

SELECT *
FROM ITEM
ORDER BY PRICE
LIMIT 1;

SELECT count(*) AS COUNT, ITEM_ID
FROM SALES_ORDER_LINE
GROUP BY ITEM_ID
ORDER BY COUNT DESC
LIMIT 1;

SELECT count(*) AS COUNT, ITEM_ID
FROM SALES_ORDER_LINE
GROUP BY ITEM_ID
ORDER BY COUNT
LIMIT 1;

SELECT count(*) AS COUNT, CUSTOMER_ID
FROM SALES_ORDER
GROUP BY CUSTOMER_ID
ORDER BY COUNT DESC
LIMIT 1;

SELECT count(DISTINCT (CUSTOMER_ID)) AS COUNT, COUNTRY
FROM ADDRESS
GROUP BY COUNTRY;

SELECT sum(PRICE) AS TOTAL_PRICE, ORDER_ID
FROM SALES_ORDER_LINE
GROUP BY ORDER_ID
ORDER BY TOTAL_PRICE DESC;