CREATE TABLE SALES_ORDER
(
    ORDER_ID    VARCHAR(10) NOT NULL,
    CUSTOMER_ID INT4        NOT NULL,
    STATUS      VARCHAR(20) NOT NULL,
    CREATED_ON  TIMESTAMP   NOT NULL,
    UPDATED_ON  TIMESTAMP   NOT NULL,
    PRIMARY KEY (ORDER_ID)
);

CREATE TABLE SALES_ORDER_LINE
(
    ORDER_ID    VARCHAR(10) NOT NULL,
    LINE_NUMBER INT4        NOT NULL,
    ITEM_ID     VARCHAR(10) NOT NULL,
    QUANTITY    INT4        NOT NULL,
    PRICE       DECIMAL     NOT NULL,
    PRIMARY KEY (ORDER_ID, LINE_NUMBER)
);

CREATE TABLE ITEM
(
    ID    VARCHAR(10) NOT NULL,
    NAME  VARCHAR(10) NOT NULL,
    PRICE DECIMAL     NOT NULL,
    PRIMARY KEY (ID)
);


ALTER TABLE IF EXISTS SALES_ORDER
    ADD CONSTRAINT FK_SALES_ORDER_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID);

ALTER TABLE IF EXISTS SALES_ORDER_LINE
    ADD CONSTRAINT FK_SALES_ORDER_LINE_ORDER_ID FOREIGN KEY (ORDER_ID) REFERENCES SALES_ORDER (ORDER_ID);

ALTER TABLE IF EXISTS SALES_ORDER_LINE
    ADD CONSTRAINT FK_SALES_ORDER_LINE_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ID);