CREATE TABLE PERSON
(
    ID   INT4        NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE SPOUSE
(
    PERSON_ID INT4 NOT NULL,
    NAME      VARCHAR(50),
    PRIMARY KEY (PERSON_ID)
);

ALTER TABLE SPOUSE
    ADD CONSTRAINT FK_SPOUSE FOREIGN KEY (PERSON_ID) REFERENCES PERSON(ID);