SELECT *
FROM CUSTOMER;

SELECT *
FROM CUSTOMER
WHERE GRADE = 99;

SELECT *
FROM CUSTOMER
WHERE GRADE > 75;

SELECT *
FROM CUSTOMER
WHERE CREATED_ON BETWEEN '2008-01-01' AND '2020-01-01';

SELECT *
FROM CUSTOMER
WHERE CREATED_ON >= '2020-01-01';


SELECT *
FROM CUSTOMER
WHERE GRADE > 75
  AND CREATED_ON >= '2020-01-01'
  AND ACTIVE = TRUE;

SELECT *
FROM CUSTOMER
ORDER BY CREATED_ON ASC;

SELECT *
FROM CUSTOMER
ORDER BY GRADE DESC;

SELECT *
FROM CUSTOMER
WHERE GRADE > 75
ORDER BY GRADE DESC;

SELECT *
FROM CUSTOMER
ORDER BY GRADE, CREATED_ON;

SELECT DISTINCT GRADE
FROM CUSTOMER
ORDER BY GRADE;

SELECT *
FROM CUSTOMER
WHERE NAME LIKE '%Buy%';

SELECT *
FROM CUSTOMER
WHERE GRADE > 75
ORDER BY GRADE DESC
LIMIT 1;

SELECT COUNT(*) AS NBR
FROM CUSTOMER
WHERE GRADE > 75;

SELECT NAME, GRADE AS LOYALTY
FROM CUSTOMER;

SELECT count(*) AS NBR_OF_CUSTOMERS, GRADE
FROM CUSTOMER
GROUP BY GRADE;

SELECT *
FROM ITEM
WHERE ID NOT IN (SELECT ITEM_ID FROM SALES_ORDER_LINE);

SELECT *
FROM ITEM I
WHERE NOT exists(SELECT ITEM_ID FROM SALES_ORDER_LINE L WHERE L.ITEM_ID = I.ID);